version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12

  build:
    commands:
      - npm install
      - npm run build

  post_build:
    commands:
      - pwd

artifacts:
  files:
    - "**/*"
    - "../appspec.yml"
    - "../scripts/*"
    # - build/*

    # - location
  name: avengers-todo-$(date +%Y-%m-%d)
  base-directory: build
  #discard-paths: yes
#cache:
#paths:
# - paths
